// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwPfu_ktAvQpUhbdKPQn7aQJCqyE-x3T0',
    appId: '1:268782084241:web:cdf035481fc353b0545f30',
    messagingSenderId: '268782084241',
    projectId: 'moviesapp-c5a1f',
    authDomain: 'moviesapp-c5a1f.firebaseapp.com',
    storageBucket: 'moviesapp-c5a1f.firebasestorage.app',
    measurementId: 'G-J0PNK695HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2lFDcTU_Hb8Nb5LmlTCX1lTwmPWVVFc',
    appId: '1:268782084241:android:1a84bd6216f63c05545f30',
    messagingSenderId: '268782084241',
    projectId: 'moviesapp-c5a1f',
    storageBucket: 'moviesapp-c5a1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPs1WEN4M7dzun3v8F5ic7qlGpkH74iRw',
    appId: '1:268782084241:ios:3c34ebd4fd3f1245545f30',
    messagingSenderId: '268782084241',
    projectId: 'moviesapp-c5a1f',
    storageBucket: 'moviesapp-c5a1f.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPs1WEN4M7dzun3v8F5ic7qlGpkH74iRw',
    appId: '1:268782084241:ios:3c34ebd4fd3f1245545f30',
    messagingSenderId: '268782084241',
    projectId: 'moviesapp-c5a1f',
    storageBucket: 'moviesapp-c5a1f.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwPfu_ktAvQpUhbdKPQn7aQJCqyE-x3T0',
    appId: '1:268782084241:web:03822dfe2c6e789f545f30',
    messagingSenderId: '268782084241',
    projectId: 'moviesapp-c5a1f',
    authDomain: 'moviesapp-c5a1f.firebaseapp.com',
    storageBucket: 'moviesapp-c5a1f.firebasestorage.app',
    measurementId: 'G-3CN7VQHDLM',
  );
}
