// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzuh0L0i2QZ3Aw3VrGznK88_2fVAhsLg4',
    appId: '1:891924159632:web:cfa3e070fa76aefb3bcc15',
    messagingSenderId: '891924159632',
    projectId: 'moviesapp-ac07b',
    authDomain: 'moviesapp-ac07b.firebaseapp.com',
    storageBucket: 'moviesapp-ac07b.firebasestorage.app',
    measurementId: 'G-W4CF72H4S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3W9XXThRkvJYIQD1XuP-d4etmI7Z5DM',
    appId: '1:891924159632:android:8fb8fb4d6e6008743bcc15',
    messagingSenderId: '891924159632',
    projectId: 'moviesapp-ac07b',
    storageBucket: 'moviesapp-ac07b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_2HhHcfZ-0tOzZav8tv3FQ7o6nvKV7_8',
    appId: '1:891924159632:ios:a2b74e0b0661dd7e3bcc15',
    messagingSenderId: '891924159632',
    projectId: 'moviesapp-ac07b',
    storageBucket: 'moviesapp-ac07b.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_2HhHcfZ-0tOzZav8tv3FQ7o6nvKV7_8',
    appId: '1:891924159632:ios:a2b74e0b0661dd7e3bcc15',
    messagingSenderId: '891924159632',
    projectId: 'moviesapp-ac07b',
    storageBucket: 'moviesapp-ac07b.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzuh0L0i2QZ3Aw3VrGznK88_2fVAhsLg4',
    appId: '1:891924159632:web:7df028dcacc956003bcc15',
    messagingSenderId: '891924159632',
    projectId: 'moviesapp-ac07b',
    authDomain: 'moviesapp-ac07b.firebaseapp.com',
    storageBucket: 'moviesapp-ac07b.firebasestorage.app',
    measurementId: 'G-4M5W6QRZ4N',
  );

}